---
title: "aerscreen example: Dispersion with buildings vs. no buildings"
author: "MPCA - Risk evaluation and air modeling, EAO"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{aerscreen example: Dispersion with buildings vs. no buildings}
---


## Mission

Compare the AERSCREEN dispersion results for a facility with buidings nearby to the results if the buildings are removed.

## Install AERSCREEN and supporting models to 'EPA' folder
```{r }
library(installEPA)
#install_epa(c("aerscreen", "bpip", "aermod", "aermap","makemet"), "EPA")

```


## Create new aerscreen table
```{r }
#library(aerscreen)
#aer_inp <- aerscreen_tbl()

library(knitr)
#kable(aer_inp)
```

## Create aerscreen input file
```{r }
#write_aerscreen(aer_inp, "no_builds.inp")
```

## Run aerscreen
```{r }
#run_aerscreen("no_builds.inp", "no_builds_results")
```

## Read results
```{r }
#results <- read_aerscreen_out("no_builds_results.out", as_text = FALSE)

#kable(results)
```
